services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: production
      args:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
        MONGO_URI: mongodb://root:password@mongo:27017
        NODE_ENV: production
        FRONTEND_PORT: 8080
        BACKEND_PORT: 3001
        MONGO_PORT: 27017
        VITE_SEARCHES_STATS_API_URL: http://localhost:3001
        VITE_SWAPI_API_URL: https://www.swapi.tech/api/
      environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_URI: mongodb://root:password@mongo:27017
      NODE_ENV: production
      FRONTEND_PORT: 8080
      BACKEND_PORT: 3001
      MONGO_PORT: 27017
      VITE_SEARCHES_STATS_API_URL: http://localhost:3001
      VITE_SWAPI_API_URL: https://www.swapi.tech/api/
    ports:
      - "${BACKEND_PORT}:3001"
    volumes:
      - ./backend:/app/backend
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: production
      args:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
        MONGO_URI: mongodb://root:password@mongo:27017
        NODE_ENV: production
        FRONTEND_PORT: 8080
        BACKEND_PORT: 3001
        MONGO_PORT: 27017
        VITE_SEARCHES_STATS_API_URL: http://localhost:3001
        VITE_SWAPI_API_URL: https://www.swapi.tech/api/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_URI: mongodb://root:password@mongo:27017
      NODE_ENV: production
      FRONTEND_PORT: 8080
      BACKEND_PORT: 3001
      MONGO_PORT: 27017
      VITE_SEARCHES_STATS_API_URL: http://localhost:3001
      VITE_SWAPI_API_URL: https://www.swapi.tech/api/
    volumes:
      - ./frontend:/app