services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: development
    ports:
      - "${BACKEND_PORT}:3001"
    volumes:
      - ./backend:/app/backend
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: development
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend:/app